// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbUEKIQRhjDxBTYiMT1JPUnObq0Abuhw',
    appId: '1:1021520929741:web:27d7b9e35c1b621b009a84',
    messagingSenderId: '1021520929741',
    projectId: 'cape-2534d',
    authDomain: 'cape-2534d.firebaseapp.com',
    storageBucket: 'cape-2534d.firebasestorage.app',
    measurementId: 'G-9JP3F3S24B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtgyTgmRw8Jk-DKG35BRwDXeEti7yemjQ',
    appId: '1:1021520929741:android:24a297334e7b46fa009a84',
    messagingSenderId: '1021520929741',
    projectId: 'cape-2534d',
    storageBucket: 'cape-2534d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMPGLqS5JXpvYxN7TSr7XMqplnVJZIPSY',
    appId: '1:1021520929741:ios:c27a21c383ffd3a5009a84',
    messagingSenderId: '1021520929741',
    projectId: 'cape-2534d',
    storageBucket: 'cape-2534d.firebasestorage.app',
    iosBundleId: 'com.pierre.capsecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMPGLqS5JXpvYxN7TSr7XMqplnVJZIPSY',
    appId: '1:1021520929741:ios:ccacc2b09250353e009a84',
    messagingSenderId: '1021520929741',
    projectId: 'cape-2534d',
    storageBucket: 'cape-2534d.firebasestorage.app',
    iosBundleId: 'com.example.capSecureMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbUEKIQRhjDxBTYiMT1JPUnObq0Abuhw',
    appId: '1:1021520929741:web:1c00c64e1ec27c51009a84',
    messagingSenderId: '1021520929741',
    projectId: 'cape-2534d',
    authDomain: 'cape-2534d.firebaseapp.com',
    storageBucket: 'cape-2534d.firebasestorage.app',
    measurementId: 'G-QGGVLME8BG',
  );
}
